name: shellcheck-isopatch
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  shellcheck:
    name: run shellcheck to verify isopatch.sh
    runs-on: ubuntu-22.04
    steps:
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v3

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: isogenerator
          tags: builder
          containerfiles: |
            ./Containerfile
      - name: run shellcheck
        run: ./util/shellcheck isopatch.sh

  isopatch-test:
    name: test isopatch by running it
    runs-on: ubuntu-22.04
    container:
      image: fedora:38
    steps:
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo dnf install \
            --disablerepo='*' \
            --enablerepo='fedora,updates' \
            --setopt install_weak_deps=0 \
            --assumeyes \
            $(cat deps.txt)

      - name: fetch net installer to patch
        run: |
          curl -L $EVERYTHING_INSTALLER_URL -o Fedora-Everything-netinst-x86_64.iso
        env:
          EVERYTHING_INSTALLER_URL: https://mirror.fcix.net/fedora/linux/development/38/Everything/x86_64/os/images/boot.iso

      - name: run isopatch.sh
        run: |
          ./isopatch.sh Fedora-Everything-netinst-x86_64.iso ublue-test.iso
